### PR TITLE
Remove InstallHint property by finding on the fly the version to install

### LINKED ISSUE #3: Remove InstallHint property
If I understand correctly the README, the hint is "static" and is determined using `InstallHint="npm install date-fns@1.30"`

I think we could remove the `InstallHint` parameter because we already have all the infos needed to generate it.

1. Detect if the project is using `yarn` or `npm`. If the repo contains a `yarn.lock` then it's using `yarn`
2. Extract the version from `>= 1.30.0`
3. Generates `{Command} install {Package}@{Version}`

### PR DESCRIPTION
**Pull request by MangelMaxime**
Fix #3

Included in this PR:

- Remove the `InstallHint` property
- Resolve the version to install using `yarn info <package> versions --json` or `npm show <package> versions --json`
- Add the possibility to configure `LowestMatching` globally
- Add the possibility to override the global `LowestMatching` per dependency
- Refactor to use `types` instead of `tuples` because I was adding a new one with `LowestMatching`

When adding the new `types` I tried to find "good" names but I am not certain of them. If you come up with better naming don't hesitate to tell me. :)

⚠️ I tried to add `LowestMatching` to `NpmDependencies` but it made `ProjectCracker` crash. `dotnet restore` was working fine. So I guess the `ProjectCracker` library has a bug/limitation here.

This is for this reason, that I added `<Strategy LowestMatching="false" />` as a child of `NpmDependencies` node.

If `<Strategy LowestMatching="false" />` is not set, then the resolution is set to `LowestMatching = true`.

Example of output:

## By default `LowestMatching` is set to `true`

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Main.fs" />
    </ItemGroup>
    <PropertyGroup>
        <NpmDependencies>
            <NpmPackage Name="date-fns" Version=">= 1.30.0"/>
            <NpmPackage Name="bulma" Version=">= 0.6.0" />
            <NpmPackage Name="password-generator" Version=">= 1.0.0"/>
        </NpmDependencies>
    </PropertyGroup>
</Project>
```

```
[17:45:21 INF] Analyzing project /Users/maximemangel/Workspaces/Github/Zaid-Ajaj/FemtoTest/NpmPackageNotInstalled/NpmPackageNotInstalled.fsproj
[17:45:24 INF] Resolution strategy for NpmPackageNotInstalled is lowest matching: True
[17:45:24 INF] 
[17:45:24 ERR] NpmPackageNotInstalled depends on npm package 'date-fns'
[17:45:24 ERR]   | -- Required range >= 1.30.0 found in project file
[17:45:24 ERR]   | -- Missing 'date-fns' in package.json
[17:45:25 ERR]   | -- Resolve this issue using 'npm install date-fns@1.30.1'
[17:45:25 INF] 
[17:45:25 ERR] NpmPackageNotInstalled depends on npm package 'bulma'
[17:45:25 ERR]   | -- Required range >= 0.6.0 found in project file
[17:45:25 ERR]   | -- Missing 'bulma' in package.json
[17:45:25 ERR]   | -- Resolve this issue using 'npm install bulma@0.6.0'
[17:45:25 INF] 
[17:45:25 ERR] NpmPackageNotInstalled depends on npm package 'password-generator'
[17:45:25 ERR]   | -- Required range >= 1.0.0 found in project file
[17:45:25 ERR]   | -- Missing 'password-generator' in package.json
[17:45:26 ERR]   | -- Resolve this issue using 'npm install password-generator@1.0.0'
```

## Set `LowestMatching` to `false`

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Main.fs" />
    </ItemGroup>
    <PropertyGroup>
        <NpmDependencies>
            <Strategy LowestMatching="false" />
            <NpmPackage Name="date-fns" Version=">= 1.30.0"/>
            <NpmPackage Name="bulma" Version=">= 0.6.0"/>
            <NpmPackage Name="password-generator" Version=">= 1.0.0"/>
        </NpmDependencies>
    </PropertyGroup>
</Project>
```

```
[17:46:46 INF] Analyzing project /Users/maximemangel/Workspaces/Github/Zaid-Ajaj/FemtoTest/NpmPackageNotInstalled/NpmPackageNotInstalled.fsproj
[17:46:49 INF] Resolution strategy for NpmPackageNotInstalled is lowest matching: False
[17:46:49 INF] 
[17:46:49 ERR] NpmPackageNotInstalled depends on npm package 'date-fns'
[17:46:49 ERR]   | -- Required range >= 1.30.0 found in project file
[17:46:49 ERR]   | -- Missing 'date-fns' in package.json
[17:46:50 ERR]   | -- Resolve this issue using 'npm install date-fns@1.30.1'
[17:46:50 INF] 
[17:46:50 ERR] NpmPackageNotInstalled depends on npm package 'bulma'
[17:46:50 ERR]   | -- Required range >= 0.6.0 found in project file
[17:46:50 ERR]   | -- Missing 'bulma' in package.json
[17:46:51 ERR]   | -- Resolve this issue using 'npm install bulma@0.7.5'
[17:46:51 INF] 
[17:46:51 ERR] NpmPackageNotInstalled depends on npm package 'password-generator'
[17:46:51 ERR]   | -- Required range >= 1.0.0 found in project file
[17:46:51 ERR]   | -- Missing 'password-generator' in package.json
[17:46:51 ERR]   | -- Resolve this issue using 'npm install password-generator@2.2.0'
```

## Override `LowestMatching` for `bulma` only

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Main.fs" />
    </ItemGroup>
    <PropertyGroup>
        <NpmDependencies>
            <NpmPackage Name="date-fns" Version=">= 1.30.0"/>
            <NpmPackage Name="bulma" Version=">= 0.6.0" LowestMatching="false"/>
            <NpmPackage Name="password-generator" Version=">= 1.0.0"/>
        </NpmDependencies>
    </PropertyGroup>
</Project>
```

```
[17:48:18 INF] Analyzing project /Users/maximemangel/Workspaces/Github/Zaid-Ajaj/FemtoTest/NpmPackageNotInstalled/NpmPackageNotInstalled.fsproj
[17:48:21 INF] Resolution strategy for NpmPackageNotInstalled is lowest matching: True
[17:48:21 INF] 
[17:48:21 ERR] NpmPackageNotInstalled depends on npm package 'date-fns'
[17:48:21 ERR]   | -- Required range >= 1.30.0 found in project file
[17:48:21 ERR]   | -- Missing 'date-fns' in package.json
[17:48:22 ERR]   | -- Resolve this issue using 'npm install date-fns@1.30.1'
[17:48:22 INF] 
[17:48:22 ERR] NpmPackageNotInstalled depends on npm package 'bulma'
[17:48:22 ERR]   | -- Required range >= 0.6.0 found in project file
[17:48:22 ERR]   | -- Missing 'bulma' in package.json
[17:48:23 INF]   | -- Resolution strategy override to lowest matching: False
[17:48:23 ERR]   | -- Resolve this issue using 'npm install bulma@0.7.5'
[17:48:23 INF] 
[17:48:23 ERR] NpmPackageNotInstalled depends on npm package 'password-generator'
[17:48:23 ERR]   | -- Required range >= 1.0.0 found in project file
[17:48:23 ERR]   | -- Missing 'password-generator' in package.json
[17:48:23 ERR]   | -- Resolve this issue using 'npm install password-generator@1.0.0'
```

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
This is amazing @MangelMaxime looks really good 🚀 

> Resolve the version to install using yarn info <package> versions --json

This is not needed because we can always assume `npm show <package> version` works. It is retrieving the same data as yarn is doing. Also we don't need to support different formats (say if yarn decided to change the output), this part can be removed from `packageVersions`:
```fs
| NodeManager.Yarn ->
    let res =    
       CreateProcess.fromRawCommand "yarn" [ "info"; pkg.Name; "versions"; "--json" ]
       |> CreateProcess.redirectOutput
       |> CreateProcess.ensureExitCode
       |> Proc.run
```

What happens when no version is satisfied? Maybe the library author chose a poor range that doesn't match anything, then this block will fail:
```fs
if lowestMatching then
    packageVersions
    |> Seq.cast<string>
    |> range.Satisfying
    |> Seq.head
else
    packageVersions
    |> Seq.cast<string>
    |> range.MaxSatisfying
```

> Add the possibility to configure LowestMatching globally. This is for this reason, that I added <Strategy LowestMatching="false" /> as a child of NpmDependencies node.

I think this is not needed either, the `LowestMatching` on `NpmPackage` should be enough. I would like not to add different ways of doing the same thing, per library there will only be a couple of packages so global "Strategy" node is overkill. 

> When adding the new types I tried to find "good" names but I am not certain of them. If you come up with better naming don't hesitate to tell me. :)

I think `ResolverStrategy="Min"` or `ResolverStrategy="Max"` would be better than "LowestMatching"

**Comment by MangelMaxime** [comment]
> This is not needed because we can always assume `npm show <package> version` works. It is retrieving the same data as yarn is doing. Also we don't need to support different formats (say if yarn decided to change the output), this part can be removed from `packageVersions`:
> 
> ```fsharp
> | NodeManager.Yarn ->
>     let res =    
>        CreateProcess.fromRawCommand "yarn" [ "info"; pkg.Name; "versions"; "--json" ]
>        |> CreateProcess.redirectOutput
>        |> CreateProcess.ensureExitCode
>        |> Proc.run
> ```

If you are using `yarn` it is possible that you don't have `npm` installed on your system. Yes `npm` should in general comes with `node` but it's not always guaranted. 

> What happens when no version is satisfied? Maybe the library author chose a poor range that doesn't match anything, then this block will fail:

Indeed, I forget to handle this case. I propose that in this case we say nothing. The user will see:

```
[17:48:23 ERR] NpmPackageNotInstalled depends on npm package 'password-generator'
[17:48:23 ERR]   | -- Required range >= 1.0.0 found in project file
[17:48:23 ERR]   | -- Missing 'password-generator' in package.json
```

And it should be enough for him to understand what's needed to do.

> I think this is not needed either, the LowestMatching on NpmPackage should be enough.

Ok, I will let it only on `NpmPackage` node

> I think ResolverStrategy="Min" or ResolverStrategy="Max" would be better than "LowestMatching"

Ok, I will rename it when removing the global setting.

**Comment by Zaid-Ajaj** [comment]
> Indeed, I forget to handle this case. I propose that in this case we say nothing. The user will see:
> ```
> [17:48:23 ERR] NpmPackageNotInstalled depends on npm package 'password-generator'
> [17:48:23 ERR]   | -- Required range >= 1.0.0 found in project file
> [17:48:23 ERR]   | -- Missing 'password-generator' in package.json
> ```

But the package could still be *installed* (not missing) but the installed version does not satisfy the required range provided by the library author.

For example if a library `example-lib` has versions `[1.0.0, 1.1.0, 1.2.0]` and the installed version is `1.1.0` which is visible in package.json but the library author writes this:
```xml
<NpmPackage Name="example-lib" Version=">= 2.0.0" />
```
Then no version in `[1.0.0, 1.1.0, 1.2.0]` satisfies `>= 2.0.0`. The user should see an error saying 
```
Error: No version of example-lib satisfied the required range >= 2.0.0
```
Or did you mean something else?

**Comment by MangelMaxime** [comment]
Sorry, I copied the error message from my first comment but all my output are when the package is not 
installed.

What I have in mind, is just don't propose an hint to the user because we can't determine one that's valid.

The error in the case of a version mismatch would be:

```
[17:48:23 ERR] NpmPackageNotInstalled depends on npm package 'password-generator'
[17:48:23 ERR]   | -- Required range >= 2.0.0 found in project file
[17:48:23 ERR]   | -- Used range >= 1.0.0 in package.json
[17:48:23 ERR]   | -- Installed version 1.0.0 does not satisfy required range >= 2.0.0
```

**Comment by Zaid-Ajaj** [comment]
Indeed, when we can't determine a valid version, the message you showed is perfect for it! Let me know if you are finished with the PR, I will merge it right away. Also I will publish a new version of Fable.DateFunctions with npm dependency metadata to test things out with a published package

**Comment by Zaid-Ajaj** [comment]
Alright [Fable.DateFunctions](https://github.com/Zaid-Ajaj/Fable.DateFunctions) is now published to nuget with npm dependency metadata. You take it for a spin to test things out. 

Another thing I want to test is *transitive* dependencies: 

Say I have project called `App` and I install `Fable.Elmish.React` then if I run Femto against `App` it should pick up `react >= 16.8.0` and `react-dom >= 16.8.0` from `Fable.React` (assuming we add the metadata of these npm dependencies to `Fable.React`)

**Comment by MangelMaxime** [comment]
> Alright [Fable.DateFunctions](https://github.com/Zaid-Ajaj/Fable.DateFunctions) is now published to nuget with npm dependency metadata. You take it for a spin to test things out.

Awesome :)

> Another thing I want to test is _transitive_ dependencies:
> 
> Say I have project called `App` and I install `Fable.Elmish.React` then if I run Femto against `App` it should pick up `react >= 16.8.0` and `react-dom >= 16.8.0` from `Fable.React` (assuming we add the metadata of these npm dependencies to `Fable.React`)

I do agree.

------------

I will work on the PR this evening and will ping you when it's ready as asked :)

**Comment by MangelMaxime** [comment]
## Required an impossible version for Bulma + Use `Fable.DateFunctions` package

`Fable.DateFunctions` has been picked correctly :)

As you can see, if I request an impossible version for Bulma, we ask the user to fix it but don't provide any hint.

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Main.fs" />
    </ItemGroup>
    <PropertyGroup>
        <NpmDependencies>
            <NpmPackage Name="bulma" Version=">= 2.0.0" ResolutionStrategy="min" />
            <NpmPackage Name="password-generator" Version="~ 1.0.0" />
        </NpmDependencies>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Fable.DateFunctions" Version="2.1.0" />
    </ItemGroup>
</Project>
```

```
[23:49:57 INF] Analyzing project /home/maxime/Workspace/Zaid-Ajaj/FemtoTests/Test.fsproj
[23:49:59 INF] 
[23:49:59 INF] Test depends on npm package 'bulma'
[23:49:59 INF]   | -- Required range >= 2.0.0 found in project file
[23:49:59 INF]   | -- Used range ^0.7.5 in package.json
[23:49:59 ERR]   | -- Installed version 0.7.5 does not satisfy required range >= 2.0.0
[23:50:00 INF] 
[23:50:00 ERR] Test depends on npm package 'password-generator'
[23:50:00 ERR]   | -- Required range ~ 1.0.0 found in project file
[23:50:00 ERR]   | -- Missing 'password-generator' in package.json
[23:50:01 ERR]   | -- Resolve this issue using 'npm install password-generator@1.0.0'
[23:50:01 INF] 
[23:50:01 ERR] Fable.DateFunctions depends on npm package 'date-fns'
[23:50:01 ERR]   | -- Required range >= 1.30.0 found in project file
[23:50:01 ERR]   | -- Missing 'date-fns' in package.json
[23:50:02 ERR]   | -- Resolve this issue using 'npm install date-fns@1.30.1'
```

I listed all the changes done in the commit description. 

The only thing I didn't do, is remove `yarn` usage to resolve the versions (see my previous comment) . `yarn` usage being really basic here, I think we can let it here for now. Otherwise, it would mean that `npm` is a hard dependency of this tools and I don't think we want that.

For me it's ready to be merged.

**Comment by Zaid-Ajaj** [comment]
Wow this thing is starting to look actually useful 🔥 🔥 :fire: 

After cleaning a couple of issue left here I will publish a version then we can start adding metadata to some core libraries (Fable.React, Fulma, MaterialUI etc) so that users can beta test this thing

**Comment by MangelMaxime** [comment]
> Wow this thing is starting to look actually useful fire fire fire

This is indeed really promising :)

Sure, we "just" need to make sure sure the XML tags are stable so we don't end up publishing several version of the packages just to change the XML tags :)

**Pull request merged**
