### PR TITLE
Fix #77: Ignore folders in node_modules starting with .

### LINKED ISSUE #77: Femto reports an error about parsing an unrelated package.json
For some reason it seems that femto tries to parse a package.json from `node_modules/.vite` and reports an error because it doesn't contain `name` property:

```
alfon@LAPTOP-V7RGQGT0 MSYS ~/repos/Lit.TodoMVC (web-component)
$ dotnet femto src
[15:59:26 INF] Analyzing project C:/Users/alfon/repos/Lit.TodoMVC/src/Lit.TodoMVC.fsproj
[15:59:26 INF] Running dotnet restore against the project
[15:59:29 INF] Using npm for package management
[15:59:30 INF] Found package.json in C:\Users\alfon\repos\Lit.TodoMVC
[15:59:30 ERR] Couldn't decode 'package.json' from C:\Users\alfon\repos\Lit.TodoMVC\node_modules\.vite\package.json. Reason: I run into the following problems:

Error at: `$`
Expecting an object with a field named `name` but instead got:
{
    "type": "module"
}

Error at: `$`
Expecting an object with a field named `version` but instead got:
{
    "type": "module"
}
[15:59:30 INF] Lit requires npm package lit
[15:59:30 INF]   | -- Required range >= 2.0.0 < 3.0.0 found in project file
[15:59:30 INF]   | -- Used range ^2.0.0 in package.json
[15:59:30 INF]   | -- ✔ Installed version 2.0.0 satisfies required range >= 2.0.0 < 3.0.0
[15:59:30 INF] Lit.Elmish requires npm package lit
[15:59:30 INF]   | -- Required range >= 2.0.0 < 3.0.0 found in project file
[15:59:30 INF]   | -- Used range ^2.0.0 in package.json
[15:59:30 INF]   | -- ✔ Installed version 2.0.0 satisfies required range >= 2.0.0 < 3.0.0
```

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Fix #77 by ignoring folders in node_modules starting with `.`

I also added recursion for scoped packages starting with `@`

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
I recommend hiding whitespace, the diff is easier to see that way :)

image

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for the fix @alfonsogarciacaro ❤️ I merged and published a new version of Femto at v0.10.0 (now targetting neet5.0) can you take it for a spin and see if the issue has been resolved?

**Comment by alfonsogarciacaro** [comment]
I'll do thanks! We have also a small Femto surprise in next Fable version ;)

**Comment by Zaid-Ajaj** [comment]
Looking forward to it @alfonsogarciacaro ❤️

**Comment by alfonsogarciacaro** [comment]
Damn! This is one of those cases where following the surrounding style was not the best thing to do 😸 Not sure why but it seems putting `then ()` in a new line and with indentation just lets the program flow go through so the error is still happening in the last version :/ I'm sending a new PR. Sorry, I should have checked it better, I had the impression it was working.

**Comment by Zaid-Ajaj** [comment]
No worries, happens to all of us 😁 merged and published again as of v0.11.0 🚀 take it for a spin and let me know how it goes

**Pull request merged**
