### PR TITLE
Add support for non-Fable packages

### PR DESCRIPTION
**Pull request by Jooseppi12**
This change makes Femto work on NuGet packages that bundle their source under "src" instead of "fable".

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello,

why do you need to bundle source code under `src`?

**Comment by Jooseppi12** [comment]
Sorry, I might have been unclear. Basically, the proposed change would allow Femto in non-Fable scenarios. Looking in `src` directory only happens if a `fable` directory doesn't exist, so Fable bindings are not affected. In our use case, we are looking into using Femto for restoring npm dependencies of WebSharper bindings, but there is no reason Femto couldn't be extended to support other tools or C#/VB/etc by simply changing where to look and for what project file.

**Comment by MangelMaxime** [comment]
I just wanted to make sure that your request had an actual usage and your didn't misunderstood how Fable worked 🙂

But as this is for another tool, I think it support for it could be added. I will wait for @Zaid-Ajaj to review this PR as he is the main maintainer of this project. If he doesn't step in, I can review it myself.

**Review by Zaid-Ajaj — APPROVED** [review]

**Comment by Zaid-Ajaj** [comment]
> In our use case, we are looking into using femto for restoring npm dependencies of WebSharper bindings

This is awesome! happy to see Femto being used for WebSharper 🎉 

Merged and published as of Femto v0.18 🚀

**Comment by granicz** [comment]
Awesome, thanks!

**Pull request merged**
